# Very simple docker-compose file to run the app on http://localhost:3000 (or http://127.0.0.1:3000).
#
# For more examples, such running Ylsoo Aivory alongside a web browsing service, see the `docs/docker` folder.

version: '3.9'

services:
  Ylsoo Aivory:
    image: ghcr.io/enricoros/ylsoo-aivory:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: [ "next", "start", "-p", "3000" ]