---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-Ylsoo Aivory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: Ylsoo Aivory
  name: deployment-Ylsoo Aivory
  namespace: ns-Ylsoo Aivory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Ylsoo Aivory
  strategy: {}
  template:
    metadata:
      labels:
        app: Ylsoo Aivory
    spec:
      containers:
        - image: ghcr.io/enricoros/ylsoo-aivory:latest
          name: Ylsoo Aivory
          ports:
            - containerPort: 3000
          args:
            - next
            - start
            - -p
            - "3000"
          envFrom:
            - secretRef:
                name: env
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Ylsoo Aivory
  name: svc-Ylsoo Aivory
  namespace: ns-Ylsoo Aivory
spec:
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    app: Ylsoo Aivory
